### ISSUE TITLE
Tracking for existing issue and future features of OCTOBOT 21.11 release

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/OctoBot#23]
Existing issues from 20.07 version:
- [ ] Need to change the Kubectl CLI to API (for Job Execution) #6 
- [X]  Adding Persistent Volume Sharing (for Dynamic Bot) #16 #30 

Feature request for next version:
- [ ] [Octo-Pro] Better Provisioning Component and Mechanism (other than Ansible)
- [X]  [Octo-Pro] Divides module/script between installation and configuration #34
- [ ] [Octo-Pro] Customized topology (currently only support Flat network)
- [X] [Octo-Play] Add command to put all files in one big “specification” file for batch/repeating execution #29 
- [X] ~~[Octo-Play] Extend the bot query command (based on a worker node, image name, status)~~ #14 
- [X] [Octo-App] Provide simple API server to allow REST API call to the orchestrator from a third-party program #31
- [X] [Octo-App] Extend the bot query command (based on a worker node, image name, status) #28
- [ ] [Octo-Bot] Integrate the monitoring bots installation into a specific worker node as a monitoring node
- [X] [Octo-Bot] CI/CD for bot development (automatically build and test when the code is uploaded) #27
- [X] [Octo-Bot] More activity bots for general file transfer #35 
- [X] [Octo-Bot] More activity bots for banking web-based environment #38 #42 
- [X] Build testing environment based on Vagrant and Kind #25 #33 
- [X] Add CI/CD through GitHub Actions for PR and Merge request #40

**Comment by ariscahyadi** [comment]
#14 is not valid feature request, because we want to separate or unique features between Octo-Play and Octo-App.

**Comment by ariscahyadi** [comment]
Please refer to #44 for uncompleted tasks.
