### ISSUE TITLE
[Documentation] Tracking any mistakes or missing information in the README

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/OctoBot#24]
The mistakes can be:

- Typos
- Broken link
- Command & output mismatch
- etc.

Missing information can be:

- Software version
- Hardware reference
- Sandboxing
- etc.

--------------------------------------------------------------------------------------

Documentation which required addition/modification:

- [x] [Octo-Pro] How to use persistent Volume
- [x] [Octo-Pro] Add config.sh documentation
- [x] [Octo-Pro] Update the documentation for install and configure
- [x] [Octo-Play] How to run batch file
- [x] [Octo-Play] Change the "addWorker" to "addExecutor"
- [x] [Octo-App] How to run API server
- [x] [Octo-App] Add moving bot documentation
- [x] [Octo-App] How to run CI/CD with DockerHub
- [x] [Main] Add contribution Workflow in "contribution.md"

**Comment by ariscahyadi** [comment]
All issues have been addressed.
