### ISSUE TITLE
Tracking for existing issue and future features of OCTOBOT current release

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/OctoBot#44]
Existing issues from the 21.11 version:
- [ ] Need to change the Kubectl CLI to API (for Job Execution)
- [ ] [Octo-Pro] Better Provisioning Component and Mechanism (other than Ansible)
- [ ] [Octo-Pro] Customized topology (currently only support Flat network)
- [ ] [Octo-Bot] Integrate the monitoring bots installation into a specific worker node as a monitoring node

Feature Request for the next version:
- [ ] [CI/CD] Test case for Octo-Pro
- [ ] [CI/CD] Test case for Octo-Play
- [ ] [CI/CD] Test case for Octo-App
- [ ] [Octo-Bot] Make bot for new environments/use cases #58
- [ ] [Octo-Bot] Enhance the bot with user behavior for web browsing #46  
- [ ] [Octo-Play] Integrate OctoBot CLI with Linux CLI

**Comment by ariscahyadi** [comment]
Replacing existing tracking #23

**Comment by ariscahyadi** [comment]
It has been replaced by issue #60
