### ISSUE TITLE
Tracking for existing issue and future features of OCTOBOT future release

### ISSUE THREAD

**Issue by ariscahyadi** [nus-ncl/OctoBot#60]
Existing issues from previous version:
- [ ] Need to change the Kubectl CLI to API (for Job Execution)
- [ ] [Octo-Pro] Better Provisioning Component and Mechanism (other than Ansible)
- [ ] [Octo-Pro] Customized topology (currently only support Flat network)
- [ ] [Octo-Bot] Integrate the monitoring bots installation into a specific worker node as a monitoring node
- [ ] [CI/CD] Test case for Octo-Pro
- [ ] [CI/CD] Test case for Octo-Play
- [ ] [CI/CD] Test case for Octo-App

Feature Request for next version:
- [ ] [Octo-Play] API for submitting specification (JSON file)
